/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TalentNetworkRouteImport } from './routes/talent-network'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConversionLiftRouteImport } from './routes/conversion-lift'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ToolsPitchDeckTemplatesRouteImport } from './routes/tools.pitch-deck-templates'
import { Route as ToolsNamingGeneratorRouteImport } from './routes/tools.naming-generator'
import { Route as ToolsBrandColorKitRouteImport } from './routes/tools.brand-color-kit'
import { Route as ServicesWebDesignRouteImport } from './routes/services.web-design'
import { Route as ServicesSocialMediaCreativeRouteImport } from './routes/services.social-media-creative'
import { Route as ServicesProductionRouteImport } from './routes/services.production'
import { Route as ServicesIllustrationDesignRouteImport } from './routes/services.illustration-design'
import { Route as ServicesEmailCreationRouteImport } from './routes/services.email-creation'
import { Route as ServicesCreativeDesignRouteImport } from './routes/services.creative-design'
import { Route as ServicesCampaignStrategyRouteImport } from './routes/services.campaign-strategy'
import { Route as ServicesBrandingServicesRouteImport } from './routes/services.branding-services'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as ServicesAiPoweredCreativeRouteImport } from './routes/services.ai-powered-creative'
import { Route as ServicesAiMarketingRouteImport } from './routes/services.ai-marketing'
import { Route as ServicesAiConsultingRouteImport } from './routes/services.ai-consulting'
import { Route as ServicesAdCreativeRouteImport } from './routes/services.ad-creative'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentNetworkRoute = TalentNetworkRouteImport.update({
  id: '/talent-network',
  path: '/talent-network',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionLiftRoute = ConversionLiftRouteImport.update({
  id: '/conversion-lift',
  path: '/conversion-lift',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const ToolsPitchDeckTemplatesRoute = ToolsPitchDeckTemplatesRouteImport.update({
  id: '/tools/pitch-deck-templates',
  path: '/tools/pitch-deck-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNamingGeneratorRoute = ToolsNamingGeneratorRouteImport.update({
  id: '/tools/naming-generator',
  path: '/tools/naming-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBrandColorKitRoute = ToolsBrandColorKitRouteImport.update({
  id: '/tools/brand-color-kit',
  path: '/tools/brand-color-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDesignRoute = ServicesWebDesignRouteImport.update({
  id: '/services/web-design',
  path: '/services/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialMediaCreativeRoute =
  ServicesSocialMediaCreativeRouteImport.update({
    id: '/services/social-media-creative',
    path: '/services/social-media-creative',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesProductionRoute = ServicesProductionRouteImport.update({
  id: '/services/production',
  path: '/services/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIllustrationDesignRoute =
  ServicesIllustrationDesignRouteImport.update({
    id: '/services/illustration-design',
    path: '/services/illustration-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEmailCreationRoute = ServicesEmailCreationRouteImport.update({
  id: '/services/email-creation',
  path: '/services/email-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreativeDesignRoute = ServicesCreativeDesignRouteImport.update({
  id: '/services/creative-design',
  path: '/services/creative-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCampaignStrategyRoute =
  ServicesCampaignStrategyRouteImport.update({
    id: '/services/campaign-strategy',
    path: '/services/campaign-strategy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBrandingServicesRoute =
  ServicesBrandingServicesRouteImport.update({
    id: '/services/branding-services',
    path: '/services/branding-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/services/automation',
  path: '/services/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiPoweredCreativeRoute =
  ServicesAiPoweredCreativeRouteImport.update({
    id: '/services/ai-powered-creative',
    path: '/services/ai-powered-creative',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiMarketingRoute = ServicesAiMarketingRouteImport.update({
  id: '/services/ai-marketing',
  path: '/services/ai-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiConsultingRoute = ServicesAiConsultingRouteImport.update({
  id: '/services/ai-consulting',
  path: '/services/ai-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdCreativeRoute = ServicesAdCreativeRouteImport.update({
  id: '/services/ad-creative',
  path: '/services/ad-creative',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/conversion-lift': typeof ConversionLiftRoute
  '/cookies': typeof CookiesRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-network': typeof TalentNetworkRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRouteWithChildren
  '/services/ad-creative': typeof ServicesAdCreativeRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-marketing': typeof ServicesAiMarketingRoute
  '/services/ai-powered-creative': typeof ServicesAiPoweredCreativeRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/branding-services': typeof ServicesBrandingServicesRoute
  '/services/campaign-strategy': typeof ServicesCampaignStrategyRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/email-creation': typeof ServicesEmailCreationRoute
  '/services/illustration-design': typeof ServicesIllustrationDesignRoute
  '/services/production': typeof ServicesProductionRoute
  '/services/social-media-creative': typeof ServicesSocialMediaCreativeRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/tools/brand-color-kit': typeof ToolsBrandColorKitRoute
  '/tools/naming-generator': typeof ToolsNamingGeneratorRoute
  '/tools/pitch-deck-templates': typeof ToolsPitchDeckTemplatesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/conversion-lift': typeof ConversionLiftRoute
  '/cookies': typeof CookiesRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-network': typeof TalentNetworkRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/ad-creative': typeof ServicesAdCreativeRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-marketing': typeof ServicesAiMarketingRoute
  '/services/ai-powered-creative': typeof ServicesAiPoweredCreativeRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/branding-services': typeof ServicesBrandingServicesRoute
  '/services/campaign-strategy': typeof ServicesCampaignStrategyRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/email-creation': typeof ServicesEmailCreationRoute
  '/services/illustration-design': typeof ServicesIllustrationDesignRoute
  '/services/production': typeof ServicesProductionRoute
  '/services/social-media-creative': typeof ServicesSocialMediaCreativeRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/tools/brand-color-kit': typeof ToolsBrandColorKitRoute
  '/tools/naming-generator': typeof ToolsNamingGeneratorRoute
  '/tools/pitch-deck-templates': typeof ToolsPitchDeckTemplatesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/conversion-lift': typeof ConversionLiftRoute
  '/cookies': typeof CookiesRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-network': typeof TalentNetworkRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRouteWithChildren
  '/services/ad-creative': typeof ServicesAdCreativeRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-marketing': typeof ServicesAiMarketingRoute
  '/services/ai-powered-creative': typeof ServicesAiPoweredCreativeRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/branding-services': typeof ServicesBrandingServicesRoute
  '/services/campaign-strategy': typeof ServicesCampaignStrategyRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/email-creation': typeof ServicesEmailCreationRoute
  '/services/illustration-design': typeof ServicesIllustrationDesignRoute
  '/services/production': typeof ServicesProductionRoute
  '/services/social-media-creative': typeof ServicesSocialMediaCreativeRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/tools/brand-color-kit': typeof ToolsBrandColorKitRoute
  '/tools/naming-generator': typeof ToolsNamingGeneratorRoute
  '/tools/pitch-deck-templates': typeof ToolsPitchDeckTemplatesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/conversion-lift'
    | '/cookies'
    | '/how-we-work'
    | '/insights'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/talent-network'
    | '/terms'
    | '/testimonials'
    | '/work'
    | '/services/ad-creative'
    | '/services/ai-consulting'
    | '/services/ai-marketing'
    | '/services/ai-powered-creative'
    | '/services/automation'
    | '/services/branding-services'
    | '/services/campaign-strategy'
    | '/services/creative-design'
    | '/services/email-creation'
    | '/services/illustration-design'
    | '/services/production'
    | '/services/social-media-creative'
    | '/services/web-design'
    | '/tools/brand-color-kit'
    | '/tools/naming-generator'
    | '/tools/pitch-deck-templates'
    | '/work/$slug'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/conversion-lift'
    | '/cookies'
    | '/how-we-work'
    | '/insights'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/talent-network'
    | '/terms'
    | '/testimonials'
    | '/services/ad-creative'
    | '/services/ai-consulting'
    | '/services/ai-marketing'
    | '/services/ai-powered-creative'
    | '/services/automation'
    | '/services/branding-services'
    | '/services/campaign-strategy'
    | '/services/creative-design'
    | '/services/email-creation'
    | '/services/illustration-design'
    | '/services/production'
    | '/services/social-media-creative'
    | '/services/web-design'
    | '/tools/brand-color-kit'
    | '/tools/naming-generator'
    | '/tools/pitch-deck-templates'
    | '/work/$slug'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/conversion-lift'
    | '/cookies'
    | '/how-we-work'
    | '/insights'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/talent-network'
    | '/terms'
    | '/testimonials'
    | '/work'
    | '/services/ad-creative'
    | '/services/ai-consulting'
    | '/services/ai-marketing'
    | '/services/ai-powered-creative'
    | '/services/automation'
    | '/services/branding-services'
    | '/services/campaign-strategy'
    | '/services/creative-design'
    | '/services/email-creation'
    | '/services/illustration-design'
    | '/services/production'
    | '/services/social-media-creative'
    | '/services/web-design'
    | '/tools/brand-color-kit'
    | '/tools/naming-generator'
    | '/tools/pitch-deck-templates'
    | '/work/$slug'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  ConversionLiftRoute: typeof ConversionLiftRoute
  CookiesRoute: typeof CookiesRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalentNetworkRoute: typeof TalentNetworkRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WorkRoute: typeof WorkRouteWithChildren
  ServicesAdCreativeRoute: typeof ServicesAdCreativeRoute
  ServicesAiConsultingRoute: typeof ServicesAiConsultingRoute
  ServicesAiMarketingRoute: typeof ServicesAiMarketingRoute
  ServicesAiPoweredCreativeRoute: typeof ServicesAiPoweredCreativeRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesBrandingServicesRoute: typeof ServicesBrandingServicesRoute
  ServicesCampaignStrategyRoute: typeof ServicesCampaignStrategyRoute
  ServicesCreativeDesignRoute: typeof ServicesCreativeDesignRoute
  ServicesEmailCreationRoute: typeof ServicesEmailCreationRoute
  ServicesIllustrationDesignRoute: typeof ServicesIllustrationDesignRoute
  ServicesProductionRoute: typeof ServicesProductionRoute
  ServicesSocialMediaCreativeRoute: typeof ServicesSocialMediaCreativeRoute
  ServicesWebDesignRoute: typeof ServicesWebDesignRoute
  ToolsBrandColorKitRoute: typeof ToolsBrandColorKitRoute
  ToolsNamingGeneratorRoute: typeof ToolsNamingGeneratorRoute
  ToolsPitchDeckTemplatesRoute: typeof ToolsPitchDeckTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-network': {
      id: '/talent-network'
      path: '/talent-network'
      fullPath: '/talent-network'
      preLoaderRoute: typeof TalentNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion-lift': {
      id: '/conversion-lift'
      path: '/conversion-lift'
      fullPath: '/conversion-lift'
      preLoaderRoute: typeof ConversionLiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/tools/pitch-deck-templates': {
      id: '/tools/pitch-deck-templates'
      path: '/tools/pitch-deck-templates'
      fullPath: '/tools/pitch-deck-templates'
      preLoaderRoute: typeof ToolsPitchDeckTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/naming-generator': {
      id: '/tools/naming-generator'
      path: '/tools/naming-generator'
      fullPath: '/tools/naming-generator'
      preLoaderRoute: typeof ToolsNamingGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/brand-color-kit': {
      id: '/tools/brand-color-kit'
      path: '/tools/brand-color-kit'
      fullPath: '/tools/brand-color-kit'
      preLoaderRoute: typeof ToolsBrandColorKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-design': {
      id: '/services/web-design'
      path: '/services/web-design'
      fullPath: '/services/web-design'
      preLoaderRoute: typeof ServicesWebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-creative': {
      id: '/services/social-media-creative'
      path: '/services/social-media-creative'
      fullPath: '/services/social-media-creative'
      preLoaderRoute: typeof ServicesSocialMediaCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/production': {
      id: '/services/production'
      path: '/services/production'
      fullPath: '/services/production'
      preLoaderRoute: typeof ServicesProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/illustration-design': {
      id: '/services/illustration-design'
      path: '/services/illustration-design'
      fullPath: '/services/illustration-design'
      preLoaderRoute: typeof ServicesIllustrationDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/email-creation': {
      id: '/services/email-creation'
      path: '/services/email-creation'
      fullPath: '/services/email-creation'
      preLoaderRoute: typeof ServicesEmailCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/creative-design': {
      id: '/services/creative-design'
      path: '/services/creative-design'
      fullPath: '/services/creative-design'
      preLoaderRoute: typeof ServicesCreativeDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/campaign-strategy': {
      id: '/services/campaign-strategy'
      path: '/services/campaign-strategy'
      fullPath: '/services/campaign-strategy'
      preLoaderRoute: typeof ServicesCampaignStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/branding-services': {
      id: '/services/branding-services'
      path: '/services/branding-services'
      fullPath: '/services/branding-services'
      preLoaderRoute: typeof ServicesBrandingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/services/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-powered-creative': {
      id: '/services/ai-powered-creative'
      path: '/services/ai-powered-creative'
      fullPath: '/services/ai-powered-creative'
      preLoaderRoute: typeof ServicesAiPoweredCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-marketing': {
      id: '/services/ai-marketing'
      path: '/services/ai-marketing'
      fullPath: '/services/ai-marketing'
      preLoaderRoute: typeof ServicesAiMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-consulting': {
      id: '/services/ai-consulting'
      path: '/services/ai-consulting'
      fullPath: '/services/ai-consulting'
      preLoaderRoute: typeof ServicesAiConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ad-creative': {
      id: '/services/ad-creative'
      path: '/services/ad-creative'
      fullPath: '/services/ad-creative'
      preLoaderRoute: typeof ServicesAdCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  ConversionLiftRoute: ConversionLiftRoute,
  CookiesRoute: CookiesRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalentNetworkRoute: TalentNetworkRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WorkRoute: WorkRouteWithChildren,
  ServicesAdCreativeRoute: ServicesAdCreativeRoute,
  ServicesAiConsultingRoute: ServicesAiConsultingRoute,
  ServicesAiMarketingRoute: ServicesAiMarketingRoute,
  ServicesAiPoweredCreativeRoute: ServicesAiPoweredCreativeRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesBrandingServicesRoute: ServicesBrandingServicesRoute,
  ServicesCampaignStrategyRoute: ServicesCampaignStrategyRoute,
  ServicesCreativeDesignRoute: ServicesCreativeDesignRoute,
  ServicesEmailCreationRoute: ServicesEmailCreationRoute,
  ServicesIllustrationDesignRoute: ServicesIllustrationDesignRoute,
  ServicesProductionRoute: ServicesProductionRoute,
  ServicesSocialMediaCreativeRoute: ServicesSocialMediaCreativeRoute,
  ServicesWebDesignRoute: ServicesWebDesignRoute,
  ToolsBrandColorKitRoute: ToolsBrandColorKitRoute,
  ToolsNamingGeneratorRoute: ToolsNamingGeneratorRoute,
  ToolsPitchDeckTemplatesRoute: ToolsPitchDeckTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
